version: "3"
services:
  # Core processes
  # Ports not required for pd0/tikv/nats because they can be resolved via the dns proxy
  dns:
    image: defreitas/dns-proxy-server
    hostname: dns.mageddo
    ports:
      - 5380:5380
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - 27017:27017

  # Processes for serving content to the user
  # Exposing ports isn't necessary but could be useful for debugging from localhost
  server:
    build: ./server
    environment:
      - NODE_ENV=development
    volumes:
      - ./data/lichess-elite-database:/pgns
    ports:
      - 8081:8081
  web:
    build: ./web
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true 
    ports:
      - 8080:8080
    volumes:
      - ./web/src:/home/pse/web/src
  proxy:
    build: ./proxy
    ports:
      - 80:80
    depends_on:
      - server
      - web
    volumes:
      - ./proxy/log:/var/log/nginx
      - /etc/letsencrypt/:/etc/letsencrypt/
